name: Python Application CI

on:
  push:
    branches:
      - main
jobs:
  call-common-ci:
    uses: Satyajeet-Sah/reusable-workflow/.github/workflows/common-ci.yml@main   
    with:
      python-version: "3.12"   
